## <u> Assignment 25 - 26th Feb </u>

#### Consider the below code to answer further questions:

In [1]:
import numpy as np

list_ = ['1' , '2', '3', '4', '5']

array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

First let's print the datatype of both variables.

In [2]:
print(f"list_ variable's type : {type(list_)}")
print(f"array_list variable's type : {type(array_list)}")

list_ variable's type : <class 'list'>
array_list variable's type : <class 'numpy.ndarray'>


You can see that there is a difference in the data type of both variables `list_` and `array_list`. The variable `list_` is the Python's list object containing string data in it. While `array_list` is the Numpy array of strings. Both of them contain string values.

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
# list_

for l in list_:
    print(f"Element Value: {l}, datatype : {type(l)}")

Element Value: 1, datatype : <class 'str'>
Element Value: 2, datatype : <class 'str'>
Element Value: 3, datatype : <class 'str'>
Element Value: 4, datatype : <class 'str'>
Element Value: 5, datatype : <class 'str'>


In [4]:
# array_list

for al in array_list:
    print(f"Element Value: {al}, datatype : {type(al)}")

Element Value: 1, datatype : <class 'numpy.str_'>
Element Value: 2, datatype : <class 'numpy.str_'>
Element Value: 3, datatype : <class 'numpy.str_'>
Element Value: 4, datatype : <class 'numpy.str_'>
Element Value: 5, datatype : <class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
array_list

array([1, 2, 3, 4, 5])

#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes. There will be difference in datatypes of both variable `list_` and `array_list`.

We converted datatype of `array_list` elements from `str` to `int`. But for the `list_1` has still `str` datatype for its elements. Let's print them both.

In [7]:
for l in list_:
    print(f"Element Value: {l}, datatype : {type(l)}")

Element Value: 1, datatype : <class 'str'>
Element Value: 2, datatype : <class 'str'>
Element Value: 3, datatype : <class 'str'>
Element Value: 4, datatype : <class 'str'>
Element Value: 5, datatype : <class 'str'>


In [8]:
for al in array_list:
    print(f"Element Value: {al}, datatype : {type(al)}")

Element Value: 1, datatype : <class 'numpy.int32'>
Element Value: 2, datatype : <class 'numpy.int32'>
Element Value: 3, datatype : <class 'numpy.int32'>
Element Value: 4, datatype : <class 'numpy.int32'>
Element Value: 5, datatype : <class 'numpy.int32'>


#### Consider the below code to answer further questions:

In [9]:
import numpy as np
num_list = [ [1, 2, 3], [4, 5, 6]]

num_array = np.array(object = num_list)

In [10]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

In [11]:
# shape of the num_array variable
sh = num_array.shape
print(f"Shape of 'num_array' is {sh}\nIt has {sh[0]} rows and {sh[1]} columns.")

Shape of 'num_array' is (2, 3)
It has 2 rows and 3 columns.


In [12]:
# size of the num_array variable
sz = num_array.size
print(f"Size of 'num_array' is {sz}")

Size of 'num_array' is 6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [13]:
z_arr = np.zeros((3,3))
z_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# print size and shape of 'z_arr' variable

print(f"Size of 'z_arr' is {z_arr.size}")
print(f"Shape of 'z_arr' is {z_arr.shape}")

Size of 'z_arr' is 9
Shape of 'z_arr' is (3, 3)


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [15]:
e_arr = np.eye(5)
e_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])